# Generated by Django 4.2.11 on 2026-04-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_header', models.TextField()),
                ('is_phishing', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('analysis_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '邮件分析记录',
                'verbose_name_plural': '邮件分析记录',
                'db_table': 'email_analyses',
            },
        ),
        migrations.CreateModel(
            name='PhishingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('url', 'URL特征'), ('email', '邮件特征')], max_length=20)),
                ('pattern', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=512)),
                ('severity', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': '钓鱼特征',
                'verbose_name_plural': '钓鱼特征',
                'db_table': 'phishing_features',
            },
        ),
        migrations.CreateModel(
            name='URLDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('is_phishing', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('detection_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'URL检测记录',
                'verbose_name_plural': 'URL检测记录',
                'db_table': 'url_detections',
            },
        ),
    ]
